### ISSUE TITLE
Args field in CMD cannot be unassigned

### ISSUE THREAD

**Issue by serebit** [DataDrake/cli-ng#11]
When creating a new `cmd.CMD`, if the `Args` field is left unassigned, the program fails with the following stack trace:
```
panic: reflect: call of reflect.Value.Elem on zero Value

goroutine 1 [running]:
reflect.Value.Elem(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib64/golang/src/reflect/value.go:842 +0x1a5
github.com/DataDrake/cli-ng/options.(*Parser).SetArgs(0xc00000e0a0, 0x0, 0x0, 0x7)
        /home/serebit/Code/Go/pkg/mod/github.com/!data!drake/cli-ng@v1.1.0/options/parser.go:161 +0xc8
github.com/DataDrake/cli-ng/cmd.(*RootCMD).Run(0x5e6b00)
        /home/serebit/Code/Go/pkg/mod/github.com/!data!drake/cli-ng@v1.1.0/cmd/root.go:122 +0x14d
main.main()
        /home/serebit/Code/Go/qol-assist/main.go:20 +0x2d
```
Setting `Args` to `&struct{}{}` works around this.

**Comment by DataDrake** [comment]
This is fixed in v2.
